/**
 * Dairy-Lift Enterprise Mock Dataset: Cattle Livestock Assets
 * Strict Relational Entity adhering to CattleAsset interface
 */

import { CattleAsset } from '../types/cattle';

export const CATTLE_ASSETS: CattleAsset[] = [
  {
    id: 'DL-C-001',
    rfidTag: 'DL-8824-A2',
    earTagNumber: 'IN-MH-NSK-8824',
    name: 'Radha',
    breed: 'A2_GIR_COW',
    dateOfBirth: '2021-04-14',
    assignedInvestorId: 'INV-DL-1001',
    costBasisINR: 130000,
    currentValuationINR: 142000,
    biologicalStatus: 'Milking',
    healthCondition: 'Optimal',
    lactation: {
      lactationNumber: 2,
      daysInMilk: 114,
      currentDailyYieldLiters: 15.6,
      peakYieldLiters: 18.4,
      fatPercentage: 4.75,
      snfPercentage: 9.10,
      proteinPercentage: 3.42,
    },
    telemetry: {
      dailyAverageYieldLiters: 15.2,
      liveHealthScore: 96,
      ruminationMinutesPerDay: 495,
      coreTemperatureCelsius: 38.6,
      activityIndex: 95,
      lastTelemetrySync: '2026-09-20T17:45:00Z',
      lastVetVisitDate: '2026-09-12',
      nextScheduledCheckup: '2026-10-12',
      collarBatteryLevel: 89,
      iotDeviceSerial: 'LORA-COL-8824-V2',
    },
    insurance: {
      policyNumber: 'NIA-LIVE-882419-M',
      underwriter: 'The New India Assurance Co. Ltd.',
      sumInsuredINR: 130000,
      coverageType: 'COMPREHENSIVE_LIVESTOCK_MORTALITY',
      validFrom: '2024-03-01',
      validUntil: '2027-02-28',
      status: 'ACTIVE',
    },
    farmAllocation: {
      facilityId: 'FAC-NSK-01',
      facilityName: 'Nashik Agro-Park High-Tech Dairy Unit A',
      shedNumber: 'Shed-04 (Organic Alfalfa Fed)',
      penId: 'PEN-A12',
      pastureZone: 'Pasture Sector #4',
      leadVeterinarian: 'Dr. Rajesh Deshmukh, MVSc',
    },
    performanceTier: 'A+',
    monthlyBonusContributionRate: 0.0042, // +0.42% bonus yield generated
  },
  {
    id: 'DL-C-002',
    rfidTag: 'DL-9102-A2',
    earTagNumber: 'IN-MH-NSK-9102',
    name: 'Gauri',
    breed: 'A2_GIR_COW',
    dateOfBirth: '2021-08-22',
    assignedInvestorId: 'INV-DL-1001',
    costBasisINR: 120000,
    currentValuationINR: 128000,
    biologicalStatus: 'Milking',
    healthCondition: 'Optimal',
    lactation: {
      lactationNumber: 2,
      daysInMilk: 88,
      currentDailyYieldLiters: 14.4,
      peakYieldLiters: 17.1,
      fatPercentage: 4.60,
      snfPercentage: 8.95,
      proteinPercentage: 3.38,
    },
    telemetry: {
      dailyAverageYieldLiters: 14.1,
      liveHealthScore: 94,
      ruminationMinutesPerDay: 480,
      coreTemperatureCelsius: 38.5,
      activityIndex: 92,
      lastTelemetrySync: '2026-09-20T17:42:00Z',
      lastVetVisitDate: '2026-09-12',
      nextScheduledCheckup: '2026-10-12',
      collarBatteryLevel: 92,
      iotDeviceSerial: 'LORA-COL-9102-V2',
    },
    insurance: {
      policyNumber: 'NIA-LIVE-910244-M',
      underwriter: 'The New India Assurance Co. Ltd.',
      sumInsuredINR: 120000,
      coverageType: 'COMPREHENSIVE_LIVESTOCK_MORTALITY',
      validFrom: '2024-03-01',
      validUntil: '2027-02-28',
      status: 'ACTIVE',
    },
    farmAllocation: {
      facilityId: 'FAC-NSK-01',
      facilityName: 'Nashik Agro-Park High-Tech Dairy Unit A',
      shedNumber: 'Shed-04 (Organic Alfalfa Fed)',
      penId: 'PEN-A14',
      pastureZone: 'Pasture Sector #4',
      leadVeterinarian: 'Dr. Rajesh Deshmukh, MVSc',
    },
    performanceTier: 'A',
    monthlyBonusContributionRate: 0.0034, // +0.34% bonus yield
  },
  {
    id: 'DL-C-003',
    rfidTag: 'DL-7341-A2',
    earTagNumber: 'IN-MH-NSK-7341',
    name: 'Kamadhenu',
    breed: 'A2_GIR_COW',
    dateOfBirth: '2020-11-05',
    assignedInvestorId: 'INV-DL-1002',
    costBasisINR: 135000,
    currentValuationINR: 149000,
    biologicalStatus: 'Milking',
    healthCondition: 'Optimal',
    lactation: {
      lactationNumber: 3,
      daysInMilk: 142,
      currentDailyYieldLiters: 16.8,
      peakYieldLiters: 19.5,
      fatPercentage: 4.80,
      snfPercentage: 9.15,
      proteinPercentage: 3.50,
    },
    telemetry: {
      dailyAverageYieldLiters: 16.5,
      liveHealthScore: 97,
      ruminationMinutesPerDay: 510,
      coreTemperatureCelsius: 38.6,
      activityIndex: 96,
      lastTelemetrySync: '2026-09-20T17:48:00Z',
      lastVetVisitDate: '2026-09-08',
      nextScheduledCheckup: '2026-10-08',
      collarBatteryLevel: 85,
      iotDeviceSerial: 'LORA-COL-7341-V2',
    },
    insurance: {
      policyNumber: 'NIA-LIVE-734110-M',
      underwriter: 'The New India Assurance Co. Ltd.',
      sumInsuredINR: 135000,
      coverageType: 'COMPREHENSIVE_LIVESTOCK_MORTALITY',
      validFrom: '2024-05-15',
      validUntil: '2027-05-14',
      status: 'ACTIVE',
    },
    farmAllocation: {
      facilityId: 'FAC-NSK-01',
      facilityName: 'Nashik Agro-Park High-Tech Dairy Unit A',
      shedNumber: 'Shed-02 (Elite Milkers)',
      penId: 'PEN-B02',
      pastureZone: 'Pasture Sector #2',
      leadVeterinarian: 'Dr. Anand Kulkarni, MVSc',
    },
    performanceTier: 'A+',
    monthlyBonusContributionRate: 0.0048, // +0.48% bonus
  },
  {
    id: 'DL-C-004',
    rfidTag: 'DL-7342-A2',
    earTagNumber: 'IN-MH-NSK-7342',
    name: 'Surabhi',
    breed: 'A2_GIR_COW',
    dateOfBirth: '2021-02-18',
    assignedInvestorId: 'INV-DL-1002',
    costBasisINR: 125000,
    currentValuationINR: 134000,
    biologicalStatus: 'Milking',
    healthCondition: 'Optimal',
    lactation: {
      lactationNumber: 2,
      daysInMilk: 96,
      currentDailyYieldLiters: 15.0,
      peakYieldLiters: 17.8,
      fatPercentage: 4.65,
      snfPercentage: 9.02,
      proteinPercentage: 3.40,
    },
    telemetry: {
      dailyAverageYieldLiters: 14.8,
      liveHealthScore: 95,
      ruminationMinutesPerDay: 490,
      coreTemperatureCelsius: 38.4,
      activityIndex: 94,
      lastTelemetrySync: '2026-09-20T17:40:00Z',
      lastVetVisitDate: '2026-09-08',
      nextScheduledCheckup: '2026-10-08',
      collarBatteryLevel: 94,
      iotDeviceSerial: 'LORA-COL-7342-V2',
    },
    insurance: {
      policyNumber: 'NIA-LIVE-734221-M',
      underwriter: 'The New India Assurance Co. Ltd.',
      sumInsuredINR: 125000,
      coverageType: 'COMPREHENSIVE_LIVESTOCK_MORTALITY',
      validFrom: '2024-05-15',
      validUntil: '2027-05-14',
      status: 'ACTIVE',
    },
    farmAllocation: {
      facilityId: 'FAC-NSK-01',
      facilityName: 'Nashik Agro-Park High-Tech Dairy Unit A',
      shedNumber: 'Shed-02 (Elite Milkers)',
      penId: 'PEN-B04',
      pastureZone: 'Pasture Sector #2',
      leadVeterinarian: 'Dr. Anand Kulkarni, MVSc',
    },
    performanceTier: 'A',
    monthlyBonusContributionRate: 0.0040,
  },
  {
    id: 'DL-C-005',
    rfidTag: 'DL-4029-MB',
    earTagNumber: 'IN-MH-NSK-4029',
    name: 'Yamuna',
    breed: 'MURRAH_BUFFALO',
    dateOfBirth: '2020-09-10',
    assignedInvestorId: 'INV-DL-1002',
    costBasisINR: 120000,
    currentValuationINR: 131000,
    biologicalStatus: 'Milking',
    healthCondition: 'Optimal',
    lactation: {
      lactationNumber: 3,
      daysInMilk: 130,
      currentDailyYieldLiters: 13.5,
      peakYieldLiters: 15.8,
      fatPercentage: 7.25, // Rich high-fat buffalo milk
      snfPercentage: 9.35,
      proteinPercentage: 4.10,
    },
    telemetry: {
      dailyAverageYieldLiters: 13.2,
      liveHealthScore: 93,
      ruminationMinutesPerDay: 505,
      coreTemperatureCelsius: 38.2,
      activityIndex: 90,
      lastTelemetrySync: '2026-09-20T17:35:00Z',
      lastVetVisitDate: '2026-09-08',
      nextScheduledCheckup: '2026-10-08',
      collarBatteryLevel: 88,
      iotDeviceSerial: 'LORA-COL-4029-MB',
    },
    insurance: {
      policyNumber: 'NIA-LIVE-402988-M',
      underwriter: 'The New India Assurance Co. Ltd.',
      sumInsuredINR: 120000,
      coverageType: 'COMPREHENSIVE_LIVESTOCK_MORTALITY',
      validFrom: '2024-05-15',
      validUntil: '2027-05-14',
      status: 'ACTIVE',
    },
    farmAllocation: {
      facilityId: 'FAC-NSK-01',
      facilityName: 'Nashik Agro-Park High-Tech Dairy Unit A',
      shedNumber: 'Shed-08 (Murrah Buffalo Paddock)',
      penId: 'PEN-M01',
      pastureZone: 'Water Wallowing Zone & Paddock 8',
      leadVeterinarian: 'Dr. Anand Kulkarni, MVSc',
    },
    performanceTier: 'A',
    monthlyBonusContributionRate: 0.0044,
  },
  {
    id: 'DL-C-006',
    rfidTag: 'DL-4030-MB',
    earTagNumber: 'IN-MH-NSK-4030',
    name: 'Ganga',
    breed: 'MURRAH_BUFFALO',
    dateOfBirth: '2020-10-04',
    assignedInvestorId: 'INV-DL-1002',
    costBasisINR: 120000,
    currentValuationINR: 130000,
    biologicalStatus: 'Milking',
    healthCondition: 'Optimal',
    lactation: {
      lactationNumber: 3,
      daysInMilk: 122,
      currentDailyYieldLiters: 13.0,
      peakYieldLiters: 15.2,
      fatPercentage: 7.40,
      snfPercentage: 9.40,
      proteinPercentage: 4.15,
    },
    telemetry: {
      dailyAverageYieldLiters: 12.8,
      liveHealthScore: 92,
      ruminationMinutesPerDay: 495,
      coreTemperatureCelsius: 38.3,
      activityIndex: 89,
      lastTelemetrySync: '2026-09-20T17:38:00Z',
      lastVetVisitDate: '2026-09-08',
      nextScheduledCheckup: '2026-10-08',
      collarBatteryLevel: 90,
      iotDeviceSerial: 'LORA-COL-4030-MB',
    },
    insurance: {
      policyNumber: 'NIA-LIVE-403091-M',
      underwriter: 'The New India Assurance Co. Ltd.',
      sumInsuredINR: 120000,
      coverageType: 'COMPREHENSIVE_LIVESTOCK_MORTALITY',
      validFrom: '2024-05-15',
      validUntil: '2027-05-14',
      status: 'ACTIVE',
    },
    farmAllocation: {
      facilityId: 'FAC-NSK-01',
      facilityName: 'Nashik Agro-Park High-Tech Dairy Unit A',
      shedNumber: 'Shed-08 (Murrah Buffalo Paddock)',
      penId: 'PEN-M03',
      pastureZone: 'Water Wallowing Zone & Paddock 8',
      leadVeterinarian: 'Dr. Anand Kulkarni, MVSc',
    },
    performanceTier: 'A',
    monthlyBonusContributionRate: 0.0044,
  },
  {
    id: 'DL-C-019',
    rfidTag: 'DL-5512-SH',
    earTagNumber: 'IN-MH-NSK-5512',
    name: 'Nandini',
    breed: 'SAHIWAL_COW',
    dateOfBirth: '2022-06-19',
    assignedInvestorId: 'INV-DL-1004', // Priya Sharma
    costBasisINR: 100000,
    currentValuationINR: 105000,
    biologicalStatus: 'Dry', // Transitioning into 1st calving
    healthCondition: 'Optimal',
    lactation: {
      lactationNumber: 1,
      daysInMilk: 0,
      currentDailyYieldLiters: 0.0,
      peakYieldLiters: 0.0,
      fatPercentage: 0.0,
      snfPercentage: 0.0,
      proteinPercentage: 0.0,
    },
    telemetry: {
      dailyAverageYieldLiters: 0.0,
      liveHealthScore: 91,
      ruminationMinutesPerDay: 465,
      coreTemperatureCelsius: 38.5,
      activityIndex: 88,
      lastTelemetrySync: '2026-09-20T17:30:00Z',
      lastVetVisitDate: '2026-09-14',
      nextScheduledCheckup: '2026-09-28',
      collarBatteryLevel: 96,
      iotDeviceSerial: 'LORA-COL-5512-SH',
    },
    insurance: {
      policyNumber: 'NIA-LIVE-551209-M',
      underwriter: 'The New India Assurance Co. Ltd.',
      sumInsuredINR: 100000,
      coverageType: 'COMPREHENSIVE_LIVESTOCK_MORTALITY',
      validFrom: '2024-08-01',
      validUntil: '2027-07-31',
      status: 'ACTIVE',
    },
    farmAllocation: {
      facilityId: 'FAC-NSK-01',
      facilityName: 'Nashik Agro-Park High-Tech Dairy Unit A',
      shedNumber: 'Shed-01 (Maternity & Gestation Barn)',
      penId: 'PEN-MAT-04',
      pastureZone: 'Maternity Paddock',
      leadVeterinarian: 'Dr. Rajesh Deshmukh, MVSc',
    },
    performanceTier: 'B+',
    monthlyBonusContributionRate: 0.0000, // Zero bonus during dry phase; 1.5% baseline protected by Yield Reserve Health
  },
  {
    id: 'DL-C-020',
    rfidTag: 'DL-9844-A2',
    earTagNumber: 'IN-MH-NSK-9844',
    name: 'Kaveri',
    breed: 'A2_GIR_COW',
    dateOfBirth: '2021-05-11',
    assignedInvestorId: 'INV-DL-1001', // Third asset for Arjun Mehta (Co-shared / under observation)
    costBasisINR: 125000,
    currentValuationINR: 120000,
    biologicalStatus: 'Medical Observation', // Active alert flagged
    healthCondition: 'Under Observation',
    lactation: {
      lactationNumber: 2,
      daysInMilk: 160,
      currentDailyYieldLiters: 10.4,
      peakYieldLiters: 16.5,
      fatPercentage: 4.40,
      snfPercentage: 8.70,
      proteinPercentage: 3.20,
    },
    telemetry: {
      dailyAverageYieldLiters: 11.2,
      liveHealthScore: 76,
      ruminationMinutesPerDay: 405, // Lower than normal
      coreTemperatureCelsius: 39.2, // Slight fever
      activityIndex: 72,
      lastTelemetrySync: '2026-09-20T17:50:00Z',
      lastVetVisitDate: '2026-09-20',
      nextScheduledCheckup: '2026-09-21',
      collarBatteryLevel: 87,
      iotDeviceSerial: 'LORA-COL-9844-V2',
    },
    insurance: {
      policyNumber: 'NIA-LIVE-984432-M',
      underwriter: 'The New India Assurance Co. Ltd.',
      sumInsuredINR: 125000,
      coverageType: 'COMPREHENSIVE_LIVESTOCK_MORTALITY',
      validFrom: '2024-03-01',
      validUntil: '2027-02-28',
      status: 'ACTIVE',
    },
    farmAllocation: {
      facilityId: 'FAC-NSK-01',
      facilityName: 'Nashik Agro-Park High-Tech Dairy Unit A',
      shedNumber: 'Shed-09 (Veterinary Care & Infirmary)',
      penId: 'INF-02',
      pastureZone: 'Infirmary Shaded Paddock',
      leadVeterinarian: 'Dr. Rajesh Deshmukh, MVSc',
    },
    performanceTier: 'B+',
    monthlyBonusContributionRate: 0.0015,
  },
];

export const CATTLE: Record<string, unknown>[] = CATTLE_ASSETS.map((c) => ({
  ...c,
  tagNumber: c.rfidTag,
  status: c.healthCondition === 'Optimal' ? 'healthy' : c.healthCondition === 'Under Observation' ? 'under_observation' : 'sick',
  dailyMilkYield: c.telemetry.dailyAverageYieldLiters,
  weeklyAvgYield: c.telemetry.dailyAverageYieldLiters,
  monthlyAvgYield: c.telemetry.dailyAverageYieldLiters,
  investorId: c.assignedInvestorId,
  purchasePrice: c.costBasisINR,
  currentValuation: c.currentValuationINR,
  insuranceCoverage: c.insurance.sumInsuredINR,
  lastMilked: '2026-09-20T17:00:00Z',
  vaccinations: [],
  healthLogs: [],
  calfDetails: [],
}));

// Legacy interface aliases for backward compatibility during phased UI rewrite
export type Cattle = Record<string, unknown>;
export type Vaccination = Record<string, unknown>;
export type HealthLog = Record<string, unknown>;
export type CalfDetail = Record<string, unknown>;

