export interface Product {
  id: string;
  name: string;
  category: string;
  price: number;
  originalPrice?: number;
  unit: string;
  image: string;
  badge?: string | null;
  badgeColor?: string | null;
  rating: number;
  reviewCount: number;
  deliveryTime: string;
  inStock: boolean;
  description: string;
  highlights: string[];
  origin: string;
  fat?: string;
  protein?: string;
}

export const CATEGORIES = [
  { id: 'all', label: 'All Products', icon: '🛒' },
  { id: 'milk', label: 'Fresh Milk', icon: '🥛' },
  { id: 'ghee', label: 'Pure Ghee', icon: '🫙' },
  { id: 'paneer', label: 'Paneer', icon: '🧀' },
  { id: 'butter', label: 'Butter', icon: '🧈' },
  { id: 'yogurt', label: 'Yogurt & Curd', icon: '🍦' },
  { id: 'cheese', label: 'Cheese', icon: '🫕' },
  { id: 'cream', label: 'Cream & Khoa', icon: '🍶' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p001',
    name: 'A2 Gir Cow Full Cream Milk',
    category: 'milk',
    price: 89,
    originalPrice: 110,
    unit: '1 Litre',
    image: '/images/product_a2_milk.jpg',
    badge: 'BESTSELLER',
    badgeColor: 'gold',
    rating: 4.9,
    reviewCount: 2847,
    deliveryTime: '12 mins',
    inStock: true,
    description: 'Pure A2 beta-casein milk from our ethically-raised Gir cows. Rich in nutrients, easy to digest.',
    highlights: ['A2 Beta-Casein', 'No Hormones', 'Grass-Fed', 'Farm Direct'],
    origin: 'Saurashtra Farm, Gujarat',
    fat: '4.5%',
    protein: '3.5%',
  },
  {
    id: 'p002',
    name: 'Bilona Ghee (Hand-Churned)',
    category: 'ghee',
    price: 849,
    originalPrice: 999,
    unit: '500 ml',
    image: '/images/product_ghee.jpg',
    badge: 'PREMIUM',
    badgeColor: 'gold',
    rating: 4.95,
    reviewCount: 1623,
    deliveryTime: '15 mins',
    inStock: true,
    description: 'Traditionally hand-churned from A2 curd using the ancient bilona method. Pure gold in a jar.',
    highlights: ['Hand-Churned', 'Bilona Method', 'A2 Sourced', 'High Butyrate'],
    origin: 'Dairy-Lift Reserve Farm, Rajasthan',
    fat: '99.8%',
    protein: '0.1%',
  },
  {
    id: 'p003',
    name: 'Farm-Fresh Paneer (Soft)',
    category: 'paneer',
    price: 149,
    originalPrice: 180,
    unit: '200g',
    image: '/images/product_paneer.jpg',
    badge: 'FRESH TODAY',
    badgeColor: 'green',
    rating: 4.8,
    reviewCount: 3201,
    deliveryTime: '10 mins',
    inStock: true,
    description: 'Made fresh every morning from whole milk. Soft, crumbly, and packed with protein.',
    highlights: ['Made Fresh Daily', 'High Protein', 'No Preservatives', 'Vegetarian Rennet'],
    origin: 'Dairy-Lift Processing Unit, Pune',
    fat: '22%',
    protein: '18%',
  },
  {
    id: 'p004',
    name: 'White Butter (Makhan)',
    category: 'butter',
    price: 199,
    originalPrice: 240,
    unit: '250g',
    image: '/images/product_ghee.jpg',
    badge: 'TRADITIONAL',
    badgeColor: 'amber',
    rating: 4.7,
    reviewCount: 987,
    deliveryTime: '12 mins',
    inStock: true,
    description: 'Unsalted white butter made from fresh cream. The authentic taste of a desi kitchen.',
    highlights: ['Unsalted', 'Fresh Cream', 'No Additives', 'Rich in CLA'],
    origin: 'Punjab Partner Farm',
    fat: '80%',
    protein: '1%',
  },
  {
    id: 'p005',
    name: 'Greek-Style Hung Curd',
    category: 'yogurt',
    price: 129,
    originalPrice: 150,
    unit: '400g',
    image: '/images/dairy_products_collection.jpg',
    badge: null,
    rating: 4.6,
    reviewCount: 1456,
    deliveryTime: '12 mins',
    inStock: true,
    description: 'Thick, protein-rich hung curd strained overnight. Perfect for dips, marinades, and smoothies.',
    highlights: ['High Protein (10g/100g)', 'Probiotic Rich', 'Zero Sugar', 'Live Cultures'],
    origin: 'Dairy-Lift Processing Unit, Pune',
    fat: '3.5%',
    protein: '10%',
  },
  {
    id: 'p006',
    name: 'Aged Cheddar Block',
    category: 'cheese',
    price: 389,
    originalPrice: 450,
    unit: '200g',
    image: '/images/dairy_products_collection.jpg',
    badge: '18 MONTHS AGED',
    badgeColor: 'amber',
    rating: 4.8,
    reviewCount: 743,
    deliveryTime: '15 mins',
    inStock: true,
    description: 'Premium 18-month aged cheddar with a sharp, complex flavour profile. Cave matured.',
    highlights: ['18-Month Aged', 'Cave Matured', 'Rich Flavour', 'A2 Milk Based'],
    origin: 'Dairy-Lift Artisan Unit, Ooty',
    fat: '33%',
    protein: '25%',
  },
  {
    id: 'p007',
    name: 'Double Toned Milk',
    category: 'milk',
    price: 54,
    unit: '1 Litre',
    image: '/images/product_a2_milk.jpg',
    badge: 'DAILY ESSENTIAL',
    badgeColor: 'blue',
    rating: 4.5,
    reviewCount: 5621,
    deliveryTime: '8 mins',
    inStock: true,
    description: 'Light, nutritious double-toned milk — ideal for everyday use and health-conscious families.',
    highlights: ['Low Fat (1.5%)', 'High Calcium', 'Pasteurised', 'FSSAI Certified'],
    origin: 'Network Partner Farms',
    fat: '1.5%',
    protein: '8.5%',
  },
  {
    id: 'p008',
    name: 'Malai Paneer (Extra-Rich)',
    category: 'paneer',
    price: 189,
    originalPrice: 220,
    unit: '200g',
    image: '/images/product_paneer.jpg',
    badge: 'CHEF\'S PICK',
    badgeColor: 'purple',
    rating: 4.85,
    reviewCount: 2109,
    deliveryTime: '10 mins',
    inStock: true,
    description: 'Extra-rich malai paneer made with full-cream milk and fresh cream. Melts in your mouth.',
    highlights: ['Full Cream', 'Extra Soft', 'Restaurant Grade', 'Made Fresh Daily'],
    origin: 'Dairy-Lift Processing Unit, Pune',
    fat: '30%',
    protein: '15%',
  },
  {
    id: 'p009',
    name: 'Reserve A2 Ghee (5-Year Bilona)',
    category: 'ghee',
    price: 1999,
    originalPrice: 2499,
    unit: '250 ml',
    image: '/images/product_ghee.jpg',
    badge: 'ULTRA PREMIUM',
    badgeColor: 'gold',
    rating: 5.0,
    reviewCount: 312,
    deliveryTime: '20 mins',
    inStock: true,
    description: 'Our finest ghee, made from cows grazing 5-year-certified pastures. Limited production, exceptional quality.',
    highlights: ['5-Year Pasture Certified', 'Limited Batch', 'Gift Packaged', 'Numbered Jar'],
    origin: 'Dairy-Lift Reserve Farm, Rajasthan',
    fat: '99.9%',
    protein: '0.05%',
  },
  {
    id: 'p010',
    name: 'Fresh Cream (35% Fat)',
    category: 'cream',
    price: 89,
    unit: '200ml',
    image: '/images/dairy_products_collection.jpg',
    badge: null,
    rating: 4.6,
    reviewCount: 867,
    deliveryTime: '12 mins',
    inStock: true,
    description: 'Rich, pourable fresh cream for desserts, pasta, and coffee. Made from whole milk.',
    highlights: ['35% Fat', 'Pasteurised', 'No Stabilisers', 'Whippable'],
    origin: 'Dairy-Lift Processing Unit, Pune',
    fat: '35%',
    protein: '2%',
  },
  {
    id: 'p011',
    name: 'Probiotic Lassi (Rose)',
    category: 'yogurt',
    price: 49,
    unit: '250ml',
    image: '/images/dairy_products_collection.jpg',
    badge: 'SUMMER HIT',
    badgeColor: 'pink',
    rating: 4.7,
    reviewCount: 2341,
    deliveryTime: '8 mins',
    inStock: true,
    description: 'Refreshing rose-flavoured lassi packed with live probiotic cultures. Natural sweetness.',
    highlights: ['Live Cultures', 'Natural Rose', 'Low Sugar', 'Probiotic Blend'],
    origin: 'Dairy-Lift Beverages Unit',
    fat: '3%',
    protein: '4%',
  },
  {
    id: 'p012',
    name: 'Salted White Butter',
    category: 'butter',
    price: 179,
    unit: '250g',
    image: '/images/product_ghee.jpg',
    badge: null,
    rating: 4.5,
    reviewCount: 1123,
    deliveryTime: '12 mins',
    inStock: true,
    description: 'Premium salted white butter with just the right pinch of Himalayan pink salt.',
    highlights: ['Himalayan Salt', 'Farm-Fresh Cream', 'No Trans Fat', 'Spreadable'],
    origin: 'Punjab Partner Farm',
    fat: '80%',
    protein: '1%',
  },
  {
    id: 'p013',
    name: 'Soft Mozzarella',
    category: 'cheese',
    price: 299,
    originalPrice: 350,
    unit: '200g',
    image: '/images/dairy_products_collection.jpg',
    badge: 'PIZZA GRADE',
    badgeColor: 'red',
    rating: 4.8,
    reviewCount: 1987,
    deliveryTime: '15 mins',
    inStock: true,
    description: 'Authentic stretched-curd mozzarella. Perfect melt, perfect stretch for your pizza.',
    highlights: ['High Moisture', 'Perfect Melt', 'No Fillers', 'Made Daily'],
    origin: 'Dairy-Lift Artisan Unit, Pune',
    fat: '22%',
    protein: '18%',
  },
  {
    id: 'p014',
    name: 'Kesar Khoa (Mava)',
    category: 'cream',
    price: 249,
    unit: '250g',
    image: '/images/dairy_products_collection.jpg',
    badge: 'FESTIVE SPECIAL',
    badgeColor: 'gold',
    rating: 4.9,
    reviewCount: 657,
    deliveryTime: '15 mins',
    inStock: true,
    description: 'Slow-cooked whole milk khoa infused with pure Kashmiri saffron. Perfect for mithai.',
    highlights: ['Kashmiri Kesar', 'Slow Cooked', 'Festival Grade', 'No Adulteration'],
    origin: 'Dairy-Lift Sweet Unit, Mathura',
    fat: '28%',
    protein: '20%',
  },
  {
    id: 'p015',
    name: 'A2 Toned Milk (Low Cal)',
    category: 'milk',
    price: 69,
    originalPrice: 85,
    unit: '1 Litre',
    image: '/images/product_a2_milk.jpg',
    badge: 'HEALTHY CHOICE',
    badgeColor: 'green',
    rating: 4.6,
    reviewCount: 3421,
    deliveryTime: '10 mins',
    inStock: true,
    description: 'All the goodness of A2 milk in a lighter, low-fat format. For health-first households.',
    highlights: ['A2 Beta-Casein', 'Low Fat (3%)', 'High Calcium', 'Grass-Fed'],
    origin: 'Saurashtra Farm, Gujarat',
    fat: '3%',
    protein: '3.5%',
  },
  {
    id: 'p016',
    name: 'Pure Cow Ghee (Standard)',
    category: 'ghee',
    price: 599,
    unit: '500 ml',
    image: '/images/product_ghee.jpg',
    badge: null,
    rating: 4.7,
    reviewCount: 4521,
    deliveryTime: '12 mins',
    inStock: true,
    description: 'Premium pure cow ghee made from pasteurised cream. Golden hue, rich aroma.',
    highlights: ['Pure Cow', 'High Smoke Point', 'FSSAI Certified', 'Rich Vitamins A, D, E'],
    origin: 'Network Partner Farms',
    fat: '99.5%',
    protein: '0.2%',
  },
  {
    id: 'p017',
    name: 'Natural Set Curd',
    category: 'yogurt',
    price: 59,
    unit: '400g',
    image: '/images/dairy_products_collection.jpg',
    badge: 'DAILY ESSENTIAL',
    badgeColor: 'blue',
    rating: 4.5,
    reviewCount: 6789,
    deliveryTime: '8 mins',
    inStock: true,
    description: 'Naturally set, creamy curd made with live bacterial cultures. Perfect with every meal.',
    highlights: ['Live Cultures', 'Naturally Set', 'No Gelatin', 'Probiotic'],
    origin: 'Dairy-Lift Processing Unit, Pune',
    fat: '4%',
    protein: '5%',
  },
  {
    id: 'p018',
    name: 'Amul-Style Processed Cheese',
    category: 'cheese',
    price: 189,
    unit: '200g',
    image: '/images/dairy_products_collection.jpg',
    badge: null,
    rating: 4.4,
    reviewCount: 2345,
    deliveryTime: '10 mins',
    inStock: true,
    description: 'Smooth, meltable processed cheese slices. Kids favourite. Great for sandwiches and burgers.',
    highlights: ['Easy Melt', 'Individually Wrapped', 'Calcium Rich', 'Pasteurised'],
    origin: 'Dairy-Lift Processing Unit, Pune',
    fat: '26%',
    protein: '16%',
  },
  {
    id: 'p019',
    name: 'Heavy Whipping Cream',
    category: 'cream',
    price: 119,
    originalPrice: 140,
    unit: '200ml',
    image: '/images/dairy_products_collection.jpg',
    badge: 'BAKERS CHOICE',
    badgeColor: 'purple',
    rating: 4.7,
    reviewCount: 1234,
    deliveryTime: '15 mins',
    inStock: true,
    description: 'Heavy whipping cream with 40% fat content. Whips to stiff peaks. Perfect for baking and desserts.',
    highlights: ['40% Fat Content', 'Stiff Peaks', 'No Carrageenan', 'Stable Whip'],
    origin: 'Dairy-Lift Processing Unit, Pune',
    fat: '40%',
    protein: '1.5%',
  },
  {
    id: 'p020',
    name: 'Lactose-Free Full Cream Milk',
    category: 'milk',
    price: 99,
    originalPrice: 120,
    unit: '1 Litre',
    image: '/images/product_a2_milk.jpg',
    badge: 'LACTOSE FREE',
    badgeColor: 'teal',
    rating: 4.8,
    reviewCount: 1876,
    deliveryTime: '12 mins',
    inStock: true,
    description: 'Full nutrition of whole milk, 100% lactose-free. Enjoy dairy without the discomfort.',
    highlights: ['0% Lactose', 'Full Cream (4.5%)', 'High Calcium', 'Enzyme Treated'],
    origin: 'Dairy-Lift Processing Unit, Pune',
    fat: '4.5%',
    protein: '3.5%',
  },
];
